// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfdexydewfplxsfpbwnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZGV4eWRld2ZwbHhzZnBid25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzY5OTAsImV4cCI6MjA2NDAxMjk5MH0.by2KVGZeEKXfKSJBF6UBFSqNkui0UqwcZqtXrruMmKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);